language: php
sudo: false

matrix:
  include:
    - php: 7.0
      env: lowest=1
    - php: 7.1

cache:
  directories:
    - $HOME/.cache/composer/files

install:
  - if [ "$lowest" = "1" ]; then composer update --prefer-lowest --prefer-stable; else composer install; fi;

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
